; testbench ESP32 reference firmware
; Build:   pio run
; Upload:  pio run -t upload
; Monitor: pio device monitor -b 9600

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
